##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore fullscreen/maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent fullscreen, class:.*
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Wine, x64 and steam_app_ border colors.
#windowrule = bordercolor rgba(ff4040ff), class:^(.*\.exe)$      # Wine
#windowrule = bordercolor rgba(ff7070ff), class:^steam_app_.*$   # Native
#windowrule = bordercolor rgba(ff7070ff), class:^(.*\.x86_64)$   # Native

# Send them to...
windowrulev2 = workspace 10 silent, class:^(.*\.exe)$
windowrulev2 = workspace 10 silent, class:^steam_app_.*$
windowrulev2 = workspace 10 silent, class:^(.*\.x86_64)$

# Auto center them
windowrulev2 = centerwindow, class:^(.*\.exe)$
windowrulev2 = centerwindow, class:^steam_app_.*$
windowrulev2 = centerwindow, class:^(.*\.x86_64)$

# Auto float and resize
windowrulev2 = float, title:^(Pipewire Volume Control)$
windowrulev2 = size 1200 1024, title:^(Pipewire Volume Control)$
windowrulev2 = float, title:^(iwgtk)$
windowrulev2 = float, class:^(iwgtk)$
windowrulev2 = size 1200 1024, title:^(iwgtk)$
windowrulev2 = float, class:^(com.github.hluk.copyq)$
windowrulev2 = size 768 1024, class:^(com.github.hluk.copyq)$
windowrulev2 = float, title:^(Dummy manual)$
windowrulev2 = size 640 768, title:^(Dummy manual)$
windowrulev2 = float, class:^(chrome-calendar.google.com__-Default)$
windowrulev2 = size 1280 768, class:^(chrome-calendar.google.com__-Default)$
windowrulev2 = float, class:^(nwg-displays)$
windowrulev2 = size 1080 768, class:^(nwg-displays)$
windowrulev2 = float, title:^(Monitor config)$
windowrulev2 = size 786 480, title:^(Monitor config)$
windowrulev2 = float, title:^(Pacman)$
windowrulev2 = size 870 768, title:^(Pacman)$
windowrulev2 = float, title:^(qalc_floating)$
windowrulev2 = size 840 768, title:^(qalc_floating)$
windowrulev2 = float, title:^(zellij_floating)$
windowrulev2 = size 1280 1024, title:^(zellij_floating)$

windowrulev2 = float, class:showmethekey-gtk
windowrulev2 = size 768 144, class:showmethekey-gtk
windowrulev2 = pin, class:showmethekey-gtk

#windowrule = opacity 0.9 override 0.9 override 1.0 override, class:.*
windowrulev2=bordercolor rgb(cba6f7),fullscreen:1
#windowrulev2=bordersize 4,fullscreen:1

windowrulev2 = maximize, title:satty
windowrulev2 = float, title:satty
windowrulev2 = size 1280 768, title:satty
windowrulev2 = centerwindow, title:nsxiv

windowrulev2 = workspace name:lock silent, title:lock_bg
windowrulev2 = fullscreenstate 2, title:lock_bg
windowrulev2 = noanim, title:lock_bg

# windowrulev2 = dimaround, title:(Power Profiles)|(Power Options)
windowrulev2 = dimaround, class:wofi

windowrule = animation popin 100%, group:1

workspace=special:magic,gapsin:24
workspace=special:magic,gapsout:72

windowrulev2 = group, class:^(kicad)$
windowrulev2 = group, class:^(blender)$

windowrulev2 = size 530 400, title:kitty
windowrulev2 = float, title:kitty
